#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 20, 2025 10:59:01 AM PST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
from tkinter import messagebox

_location = os.path.dirname(__file__)

import viewer_support_v2

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: viewer_support_v2.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class DoubleSlider(tk.Frame):
    def __init__(self, parent, from_=0, to=6000, command=None, **kwargs):
        super().__init__(parent, **kwargs)
        
        self.from_ = from_
        self.to = to
        self.command = command
        
        self.scale1 = ttk.Scale(self, from_=self.from_, to=self.to, orient=tk.HORIZONTAL)
        self.scale1.pack(fill=tk.X, side=tk.TOP)
        self.scale1.set(self.from_)
        self.scale1.bind("<B1-Motion>", self.update_scale1)
        self.scale1.bind("<ButtonRelease-1>", self.call_command)

        self.scale2 = ttk.Scale(self, from_=self.from_, to=self.to, orient=tk.HORIZONTAL)
        self.scale2.pack(fill=tk.X, side=tk.TOP)
        self.scale2.set(self.to)
        self.scale2.bind("<B1-Motion>", self.update_scale2)
        self.scale2.bind("<ButtonRelease-1>", self.call_command)

    def update_scale1(self, event):
        if self.scale1.get() >= self.scale2.get():
            self.scale1.set(self.scale2.get() - 1)
        self.call_command(None)

    def update_scale2(self, event):
        if self.scale2.get() <= self.scale1.get():
            self.scale2.set(self.scale1.get() + 1)
        self.call_command(None)

    def call_command(self, event):
        if self.command:
            self.command()

    def get(self):
        return (self.scale1.get(), self.scale2.get())

    def set(self, lower, upper):
        self.scale1.set(lower)
        self.scale2.set(upper)
    
class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1104x740+446+135")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("FTIR Viewer")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        _style_code()
        self.TScale1 = ttk.Scale(self.top,
                                 from_=0, to=6000,
                                 state=tk.NORMAL)
        self.TScale1.place(relx=0.009, rely=0.892, relheight=0.026, relwidth=0.9)
        self.TScale1.configure(length="1080")
        self.TScale1.set(0)  # Set the initial position to the leftmost side
        self.TScale1.configure(command=viewer_support_v2.update_plot_range)

        self.TScale2 = ttk.Scale(self.top,
                                 from_=0, to=6000,
                                 state=tk.NORMAL)
        self.TScale2.place(relx=0.009, rely=0.919, relheight=0.026, relwidth=0.9)
        self.TScale2.configure(length="1080")
        self.TScale2.set(6000)  # Set the initial position to the rightmost side
        self.TScale2.configure(command=viewer_support_v2.update_plot_range)

        # Replace TScale1 and TScale2 with DoubleSlider
        # self.double_slider = DoubleSlider(self.top, from_=0, to=6000,
        #                                   command = viewer_support_v2.update_plot_range)
        # self.double_slider.place(relx=0.087, rely=0.892, relheight=0.052, relwidth=0.9)        

        self.Listbox1 = tk.Listbox(self.top, selectmode=tk.EXTENDED)
        self.Listbox1.place(relx=0.083, rely=0.027, relheight=0.219, relwidth=0.341)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="-family {Courier New} -size 9")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="#000000")
        self.Listbox1.configure(selectbackground="#d9d9d9")
        self.Listbox1.configure(selectforeground="black")
        self.Listbox1.bind("<Double-1>", viewer_support_v2.on_listbox_double_click)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.014, rely=0.027, height=60, width=70)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Get 
Raw Files
(.csv)''')
        self.Button1.configure(command=viewer_support_v2.get_spectra)

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.014, rely=0.114, height=26, width=70)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Plot''')
        self.Button2.configure(command=viewer_support_v2.plot)

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.797, rely=0.027, height=26, width=137)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''Set As Background''')
        self.Button3.configure(command=viewer_support_v2.set_as_background)

        # self.Button3_1 = tk.Button(self.top)
        # self.Button3_1.place(relx=0.67, rely=0.027, height=26, width=137)
        # self.Button3_1.configure(activebackground="#d9d9d9")
        # self.Button3_1.configure(activeforeground="black")
        # self.Button3_1.configure(background="#d9d9d9")
        # self.Button3_1.configure(disabledforeground="#a3a3a3")
        # self.Button3_1.configure(font="-family {Segoe UI} -size 9")
        # self.Button3_1.configure(foreground="#000000")
        # self.Button3_1.configure(highlightbackground="#d9d9d9")
        # self.Button3_1.configure(highlightcolor="#000000")
        # self.Button3_1.configure(text='''Set As Primary''')
        # self.Button3_1.configure(command=viewer_support_v2.set_as_primary)

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.797, rely=0.068, height=26, width=137)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 9")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="#000000")
        self.Button4.configure(text='''Unset Background''')
        self.Button4.configure(command=viewer_support_v2.unset_as_background)

        # self.Button4_1 = tk.Button(self.top)
        # self.Button4_1.place(relx=0.67, rely=0.068, height=26, width=137)
        # self.Button4_1.configure(activebackground="#d9d9d9")
        # self.Button4_1.configure(activeforeground="black")
        # self.Button4_1.configure(background="#d9d9d9")
        # self.Button4_1.configure(disabledforeground="#a3a3a3")
        # self.Button4_1.configure(font="-family {Segoe UI} -size 9")
        # self.Button4_1.configure(foreground="#000000")
        # self.Button4_1.configure(highlightbackground="#d9d9d9")
        # self.Button4_1.configure(highlightcolor="#000000")
        # self.Button4_1.configure(text='''Unset As Primary''')
        # self.Button4_1.configure(command=viewer_support_v2.unset_as_primary)

        # self.Button5 = tk.Button(self.top)
        # self.Button5.place(relx=0.797, rely=0.108, height=26, width=137)
        # self.Button5.configure(activebackground="#d9d9d9")
        # self.Button5.configure(activeforeground="black")
        # self.Button5.configure(background="#d9d9d9")
        # self.Button5.configure(disabledforeground="#a3a3a3")
        # self.Button5.configure(font="-family {Segoe UI} -size 9")
        # self.Button5.configure(foreground="#000000")
        # self.Button5.configure(highlightbackground="#d9d9d9")
        # self.Button5.configure(highlightcolor="#000000")
        # self.Button5.configure(text='''Subtract Single''')
        # self.Button5.configure(command=viewer_support_v2.subtract)

        self.Button5_1 = tk.Button(self.top)
        # self.Button5_1.place(relx=0.67, rely=0.108, height=26, width=137)
        self.Button5_1.place(relx=0.797, rely=0.149, height=26, width=137)
        self.Button5_1.configure(activebackground="#d9d9d9")
        self.Button5_1.configure(activeforeground="black")
        self.Button5_1.configure(background="#d9d9d9")
        self.Button5_1.configure(disabledforeground="#a3a3a3")
        self.Button5_1.configure(font="-family {Segoe UI} -size 9")
        self.Button5_1.configure(foreground="#000000")
        self.Button5_1.configure(highlightbackground="#d9d9d9")
        self.Button5_1.configure(highlightcolor="#000000")
        self.Button5_1.configure(text='''Cancel Subtr.''')
        self.Button5_1.configure(command=viewer_support_v2.cancel_subtraction)

        self.Button5_2 = tk.Button(self.top)
        self.Button5_2.place(relx=0.928, rely=0.108, height=26, width=67)
        self.Button5_2.configure(activebackground="#d9d9d9")
        self.Button5_2.configure(activeforeground="black")
        self.Button5_2.configure(background="#d9d9d9")
        self.Button5_2.configure(disabledforeground="#a3a3a3")
        self.Button5_2.configure(font="-family {Segoe UI} -size 9")
        self.Button5_2.configure(foreground="#000000")
        self.Button5_2.configure(highlightbackground="#d9d9d9")
        self.Button5_2.configure(highlightcolor="#000000")
        self.Button5_2.configure(text='''Save Single''')

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.928, rely=0.027, height=56, width=67)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 9")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="#000000")
        self.Button6.configure(text='''Clear''')
        self.Button6.configure(command=viewer_support_v2.clear_plot)

        self.Button7 = tk.Button(self.top)
        self.Button7.place(relx=0.014, rely=0.208, height=26, width=70)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="black")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font="-family {Segoe UI} -size 9")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="#000000")
        self.Button7.configure(text='''Remove''')
        self.Button7.configure(command=viewer_support_v2.remove_selected)

        self.Button8 = tk.Button(self.top)
        self.Button8.place(relx=0.602, rely=0.027, height=56, width=67)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="black")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="#000000")
        self.Button8.configure(text='''Integrate
Peak''')

        self.Button9 = tk.Button(self.top, state = tk.DISABLED)
        self.Button9.place(relx=0.014, rely=0.249, height=26, width=70)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="black")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="#000000")
        self.Button9.configure(text='''Add Anch.''')

        self.Button9_1 = tk.Button(self.top)
        self.Button9_1.place(relx=0.928, rely=0.249, height=26, width=67)
        self.Button9_1.configure(activebackground="#d9d9d9")
        self.Button9_1.configure(activeforeground="black")
        self.Button9_1.configure(background="#d9d9d9")
        self.Button9_1.configure(disabledforeground="#a3a3a3")
        self.Button9_1.configure(font="-family {Segoe UI} -size 9")
        self.Button9_1.configure(foreground="#000000")
        self.Button9_1.configure(highlightbackground="#d9d9d9")
        self.Button9_1.configure(highlightcolor="#000000")
        self.Button9_1.configure(text='''Rm Anch.''')

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(relx=0.009, rely=0.289, relheight=0.599, relwidth=0.98)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="#000000")
        self.Canvas1.configure(insertbackground="#000000")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")
        self.Canvas1.configure(selectforeground="black")

        self.TScale3 = ttk.Scale(self.top, from_=0, to=1.0,
                                 state = tk.DISABLED)
        self.TScale3.place(relx=0.163, rely=0.254, relheight=0.027, relwidth=0.679)
        self.TScale3.configure(length="924")
        self.TScale3.configure(takefocus="")
        # self.TScale3.configure(command=viewer_support_v2.update_plot_range)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.43, rely=0.027, relheight=0.219, relwidth=0.168)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(cursor="fleur")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        # Add Treeview to Frame1
        self.tree = ttk.Treeview(self.Frame1, columns=("Column 1", "Column 2"), show='headings')
        self.tree.heading("Column 1", text="Wavenumber")
        self.tree.heading("Column 2", text="Absorbance")
        self.tree.column("Column 1", width=100)
        self.tree.column("Column 2", width=100)
        self.tree.pack(fill=tk.BOTH, expand=True)

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.602, rely=0.108, height = 56, width = 67)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="#000000")
        self.Text1.configure(insertbackground="#000000")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        # self.Message1 = tk.Message(self.top)
        # self.Message1.place(relx=0.435, rely=0.027, relheight=0.215, relwidth=0.226)
        # self.Message1.configure(background="#d9d9d9")
        # self.Message1.configure(font="-family {Segoe UI} -size 9")
        # self.Message1.configure(foreground="#000000")
        # self.Message1.configure(highlightbackground="#d9d9d9")
        # self.Message1.configure(highlightcolor="#000000")
        # self.Message1.configure(padx="1")
        # self.Message1.configure(pady="1")
        # self.Message1.configure(text='''Message''')
        # self.Message1.configure(width=249)
        
        # self.Button4_1 = tk.Button(self.top)
        # self.Button4_1.place(relx=0.67, rely=0.068, height=26, width=137)
        # self.Button4_1.configure(activebackground="#d9d9d9")
        # self.Button4_1.configure(activeforeground="black")
        # self.Button4_1.configure(background="#d9d9d9")
        # self.Button4_1.configure(disabledforeground="#a3a3a3")
        # self.Button4_1.configure(font="-family {Segoe UI} -size 9")
        # self.Button4_1.configure(foreground="#000000")
        # self.Button4_1.configure(highlightbackground="#d9d9d9")
        # self.Button4_1.configure(highlightcolor="#000000")
        # self.Button4_1.configure(text='''Unset As Primary''')
        # self.Button4_1.configure(command = viewer_support_v2.unset_as_primary)

        self.Button5_2 = tk.Button(self.top)
        self.Button5_2.place(relx=0.928, rely=0.108, height=56, width=67)
        self.Button5_2.configure(activebackground="#d9d9d9")
        self.Button5_2.configure(activeforeground="black")
        self.Button5_2.configure(background="#d9d9d9")
        self.Button5_2.configure(disabledforeground="#a3a3a3")
        self.Button5_2.configure(font="-family {Segoe UI} -size 9")
        self.Button5_2.configure(foreground="#000000")
        self.Button5_2.configure(highlightbackground="#d9d9d9")
        self.Button5_2.configure(highlightcolor="#000000")
        self.Button5_2.configure(text='''Export''')
        self.Button5_2.configure(command = viewer_support_v2.export)

        # Bind double-click event to Listbox1
        self.Listbox1.bind("<Double-1>", viewer_support_v2.on_listbox_double_click)

        self.Button5_3 = tk.Button(self.top)
        self.Button5_3.place(relx=0.797, rely=0.108, height=26, width=137)
        # self.Button5_3.place(relx=0.797, rely=0.149, height=26, width=137)
        self.Button5_3.configure(activebackground="#d9d9d9")
        self.Button5_3.configure(activeforeground="black")
        self.Button5_3.configure(background="#d9d9d9")
        self.Button5_3.configure(disabledforeground="#a3a3a3")
        self.Button5_3.configure(font="-family {Segoe UI} -size 9")
        self.Button5_3.configure(foreground="#000000")
        self.Button5_3.configure(highlightbackground="#d9d9d9")
        self.Button5_3.configure(highlightcolor="#000000")
        self.Button5_3.configure(text='''Subtract Group''')
        self.Button5_3.configure(command = viewer_support_v2.subtract_background_from_all)
        
        # self.Button5_2_1 = tk.Button(self.top)
        # self.Button5_2_1.place(relx=0.928, rely=0.149, height=26, width=67)
        # self.Button5_2_1.configure(activebackground="#d9d9d9")
        # self.Button5_2_1.configure(activeforeground="black")
        # self.Button5_2_1.configure(background="#d9d9d9")
        # self.Button5_2_1.configure(disabledforeground="#a3a3a3")
        # self.Button5_2_1.configure(font="-family {Segoe UI} -size 9")
        # self.Button5_2_1.configure(foreground="#000000")
        # self.Button5_2_1.configure(highlightbackground="#d9d9d9")
        # self.Button5_2_1.configure(highlightcolor="#000000")
        # self.Button5_2_1.configure(text='''Sav. Group''')

        self.Button9.configure(command=viewer_support_v2.add_anchor)
        self.Button9_1.configure(command=viewer_support_v2.remove_anchors)
        self.Button8.configure(command=viewer_support_v2.integrate_peak)

        # # new widgets added on 02/24/2025
        # self.Button7_1 = tk.Button(self.top)
        # self.Button7_1.place(relx=0.014, rely=0.168, height=26, width=70)
        # self.Button7_1.configure(activebackground="#d9d9d9")
        # self.Button7_1.configure(activeforeground="black")
        # self.Button7_1.configure(background="#d9d9d9")
        # self.Button7_1.configure(disabledforeground="#a3a3a3")
        # self.Button7_1.configure(font="-family {Segoe UI} -size 9")
        # self.Button7_1.configure(foreground="#000000")
        # self.Button7_1.configure(highlightbackground="#d9d9d9")
        # self.Button7_1.configure(highlightcolor="#000000")
        # self.Button7_1.configure(text='''Multi. Sel.''')
        # self.Button7_1.configure(command = viewer_support_v2.switch_multi_single)

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.insert(0, "0")
        self.Entry1.place(relx=0.912, rely=0.892, height=19, relwidth=0.076)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.bind("<Return>", viewer_support_v2.set_zoom_lower_limit)

        self.Entry1_1 = tk.Entry(self.top)
        self.Entry1_1.insert(0, "6000")
        self.Entry1_1.place(relx=0.912, rely=0.919, height=19, relwidth=0.076)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="-family {Courier New} -size 10")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="#000000")
        self.Entry1_1.configure(insertbackground="#000000")
        self.Entry1_1.configure(selectbackground="#d9d9d9")
        self.Entry1_1.configure(selectforeground="black")
        self.Entry1_1.bind("<Return>", viewer_support_v2.set_zoom_upper_limit)

        self.Entry1_2 = tk.Entry(self.top)
        self.Entry1_2.place(relx=0.083, rely=0.254, height=19, relwidth=0.076)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font="-family {Courier New} -size 10")
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="#000000")
        self.Entry1_2.configure(insertbackground="#000000")
        self.Entry1_2.configure(selectbackground="#d9d9d9")
        self.Entry1_2.configure(selectforeground="black")
        self.Entry1_2.bind("<Return>", viewer_support_v2.set_left_anchor)

        self.Entry1_2_1 = tk.Entry(self.top)
        self.Entry1_2_1.place(relx=0.844, rely=0.254, height=19, relwidth=0.076)
        self.Entry1_2_1.configure(background="white")
        self.Entry1_2_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_2_1.configure(font="-family {Courier New} -size 10")
        self.Entry1_2_1.configure(foreground="#000000")
        self.Entry1_2_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_2_1.configure(highlightcolor="#000000")
        self.Entry1_2_1.configure(insertbackground="#000000")
        self.Entry1_2_1.configure(selectbackground="#d9d9d9")
        self.Entry1_2_1.configure(selectforeground="black")
        self.Entry1_2_1.bind("<Return>", viewer_support_v2.set_right_anchor)
        

def start_up():
    viewer_support_v2.main()

if __name__ == '__main__':
    viewer_support_v2.main()
