#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 20, 2025 10:59:01 AM PST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import viewer_design2_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: viewer_design2_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1104x740+446+135")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        _style_code()
        self.TScale2 = ttk.Scale(self.top, from_=0, to=1.0)
        self.TScale2.place(relx=0.009, rely=0.919, relheight=0.026
                , relwidth=0.978)
        self.TScale2.configure(length="1080")

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.797, rely=0.068, height=26, width=137)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 9")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="#000000")
        self.Button4.configure(text='''Unset As Background''')

        self.Button4_1 = tk.Button(self.top)
        self.Button4_1.place(relx=0.67, rely=0.068, height=26, width=137)
        self.Button4_1.configure(activebackground="#d9d9d9")
        self.Button4_1.configure(activeforeground="black")
        self.Button4_1.configure(background="#d9d9d9")
        self.Button4_1.configure(disabledforeground="#a3a3a3")
        self.Button4_1.configure(font="-family {Segoe UI} -size 9")
        self.Button4_1.configure(foreground="#000000")
        self.Button4_1.configure(highlightbackground="#d9d9d9")
        self.Button4_1.configure(highlightcolor="#000000")
        self.Button4_1.configure(text='''Unset As Primary''')

        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.797, rely=0.108, height=26, width=137)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {Segoe UI} -size 9")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="#000000")
        self.Button5.configure(text='''Subtract''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.797, rely=0.027, height=26, width=137)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''Set As Background''')

        self.Button3_1 = tk.Button(self.top)
        self.Button3_1.place(relx=0.67, rely=0.027, height=26, width=137)
        self.Button3_1.configure(activebackground="#d9d9d9")
        self.Button3_1.configure(activeforeground="black")
        self.Button3_1.configure(background="#d9d9d9")
        self.Button3_1.configure(disabledforeground="#a3a3a3")
        self.Button3_1.configure(font="-family {Segoe UI} -size 9")
        self.Button3_1.configure(foreground="#000000")
        self.Button3_1.configure(highlightbackground="#d9d9d9")
        self.Button3_1.configure(highlightcolor="#000000")
        self.Button3_1.configure(text='''Set As Primary''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.014, rely=0.027, height=60, width=70)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Get 
Raw Files
(.csv)''')

        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.083, rely=0.027, relheight=0.219
                , relwidth=0.341)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="-family {Courier New} -size 9")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="#000000")
        self.Listbox1.configure(selectbackground="#d9d9d9")
        self.Listbox1.configure(selectforeground="black")

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.43, rely=0.027, relheight=0.219, relwidth=0.168)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(cursor="fleur")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.928, rely=0.027, height=56, width=67)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 9")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="#000000")
        self.Button6.configure(text='''Clear''')

        self.TScale1 = ttk.Scale(self.top, from_=0, to=1.0)
        self.TScale1.place(relx=0.009, rely=0.892, relheight=0.026
                , relwidth=0.978)
        self.TScale1.configure(length="1080")

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(relx=0.009, rely=0.289, relheight=0.599
                , relwidth=0.98)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="#000000")
        self.Canvas1.configure(insertbackground="#000000")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")
        self.Canvas1.configure(selectforeground="black")

        self.Button7 = tk.Button(self.top)
        self.Button7.place(relx=0.014, rely=0.168, height=56, width=70)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="black")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font="-family {Segoe UI} -size 9")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="#000000")
        self.Button7.configure(text='''Remove
Raw Files''')

        self.Button9 = tk.Button(self.top)
        self.Button9.place(relx=0.014, rely=0.249, height=26, width=70)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="black")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="#000000")
        self.Button9.configure(text='''Add Anch.''')

        self.Button9_1 = tk.Button(self.top)
        self.Button9_1.place(relx=0.928, rely=0.249, height=26, width=67)
        self.Button9_1.configure(activebackground="#d9d9d9")
        self.Button9_1.configure(activeforeground="black")
        self.Button9_1.configure(background="#d9d9d9")
        self.Button9_1.configure(disabledforeground="#a3a3a3")
        self.Button9_1.configure(font="-family {Segoe UI} -size 9")
        self.Button9_1.configure(foreground="#000000")
        self.Button9_1.configure(highlightbackground="#d9d9d9")
        self.Button9_1.configure(highlightcolor="#000000")
        self.Button9_1.configure(text='''Rm Anch.''')

        self.Button5_2 = tk.Button(self.top)
        self.Button5_2.place(relx=0.928, rely=0.108, height=26, width=67)
        self.Button5_2.configure(activebackground="#d9d9d9")
        self.Button5_2.configure(activeforeground="black")
        self.Button5_2.configure(background="#d9d9d9")
        self.Button5_2.configure(disabledforeground="#a3a3a3")
        self.Button5_2.configure(font="-family {Segoe UI} -size 9")
        self.Button5_2.configure(foreground="#000000")
        self.Button5_2.configure(highlightbackground="#d9d9d9")
        self.Button5_2.configure(highlightcolor="#000000")
        self.Button5_2.configure(text='''Save Net''')

        self.TScale3 = ttk.Scale(self.top, from_=0, to=1.0)
        self.TScale3.place(relx=0.082, rely=0.254, relheight=0.027
                , relwidth=0.837)
        self.TScale3.configure(length="924")
        self.TScale3.configure(takefocus="")

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.014, rely=0.114, height=36, width=70)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Plot All''')

        self.Button8 = tk.Button(self.top)
        self.Button8.place(relx=0.602, rely=0.027, height=56, width=67)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="black")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="#000000")
        self.Button8.configure(text='''Integrate
Peak''')

        self.Button5_1 = tk.Button(self.top)
        self.Button5_1.place(relx=0.67, rely=0.108, height=26, width=137)
        self.Button5_1.configure(activebackground="#d9d9d9")
        self.Button5_1.configure(activeforeground="black")
        self.Button5_1.configure(background="#d9d9d9")
        self.Button5_1.configure(disabledforeground="#a3a3a3")
        self.Button5_1.configure(font="-family {Segoe UI} -size 9")
        self.Button5_1.configure(foreground="#000000")
        self.Button5_1.configure(highlightbackground="#d9d9d9")
        self.Button5_1.configure(highlightcolor="#000000")
        self.Button5_1.configure(text='''Cancel Subtr.''')

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.602, rely=0.108, relheight=0.035, relwidth=0.061)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="#000000")
        self.Text1.configure(insertbackground="#000000")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

def start_up():
    viewer_design2_support.main()

if __name__ == '__main__':
    viewer_design2_support.main()




