#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 19, 2025 12:02:38 PM PST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1104x740+310+177
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Set As Background" 
    vTcl:DefineAlias "$top.but51" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Subtract" 
    vTcl:DefineAlias "$top.but52" "Button5" vTcl:WidgetProc "Toplevel1" 1
    listbox "$top.lis47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 -height 91 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 750 
    $top.lis47 configure -font "TkFixedFont"
    $top.lis47 insert end text
    vTcl:DefineAlias "$top.lis47" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Get 
Spectra
(.csv)" 
    vTcl:DefineAlias "$top.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Plot" 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$top.tSc55" \
        -length 1080 
    vTcl:DefineAlias "$top.tSc55" "TScale1" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can54" \
        -background #d9d9d9 -borderwidth 2 -closeenough 1.0 -height 473 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 1082 
    vTcl:DefineAlias "$top.can54" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$top.tSc56" \
        -length 1080 
    vTcl:DefineAlias "$top.tSc56" "TScale2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Set As Primary" 
    vTcl:DefineAlias "$top.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Clear" 
    vTcl:DefineAlias "$top.but53" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Remove
All" 
    vTcl:DefineAlias "$top.but47" "Button7" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes57" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Message" -width 1069 
    vTcl:DefineAlias "$top.mes57" "Message1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but51 \
        -in $top -x 0 -relx 0.797 -y 0 -rely 0.068 -width 137 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.797 -y 0 -rely 0.108 -width 137 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lis47 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.022 -width 0 -relwidth 0.707 \
        -height 0 -relheight 0.123 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.022 -width 70 -relwidth 0 \
        -height 60 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.108 -width 70 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSc55 \
        -in $top -x 0 -relx 0.009 -y 0 -rely 0.892 -width 0 -relwidth 0.978 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.can54 \
        -in $top -x 0 -relx 0.009 -y 0 -rely 0.243 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.639 -anchor nw -bordermode ignore 
    place $top.tSc56 \
        -in $top -x 0 -relx 0.009 -y 0 -rely 0.919 -width 0 -relwidth 0.978 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.797 -y 0 -rely 0.027 -width 137 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.928 -y 0 -rely 0.081 -width 67 -relwidth 0 \
        -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.928 -y 0 -rely 0.027 -width 67 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes57 \
        -in $top -x 0 -relx 0.018 -y 0 -rely 0.162 -width 0 -relwidth 0.968 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

